apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    element: prometheus
    type: zowetest
    env: test
spec: 
  selector:
    element: prometheus
    type: zowetest
    env: test
  type: LoadBalancer
  ports:
  - targetPort: 9090
    port: 9090
