apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    element: pushgateway
    type: zowetest
    env: test
spec: 
  selector:
    element: pushgateway
    type: zowetest
    env: test
  type: ClusterIP
  ports:
  - targetPort: 9091
    port: 9091
